version: "2.1"
services:
  mongodb:
    image: mongo:latest
    command: mongod --smallfiles
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
      MONGODB_USER: "${MONGODB_USER}"
      MONGODB_PASS: "${MONGODB_PASS}"
  redis:
    image: "redis:3.0"
    volumes:
      - "./data/redis:/data"
    restart: always
    command: redis-server --maxmemory 5gb
    sysctls:
      net.core.somaxconn: 512
  node:
    build: .
    image: "clout-stack/clout-auth-server:$BUILD_NUMBER"
    command: "node ."
    ports:
      - "${NODE_PORT}:80"
    environment:
      NODE_ENV: "${NODE_ENV}"
      PORT: "80"
      REDIS_HOST: "${REDIS_HOST}"
      MONGODB_HOST: "${MONGODB_HOST}"
      MONGODB_USER: "${MONGODB_USER}"
      MONGODB_PASS: "${MONGODB_PASS}"
      SESSION_SECRET: "${SESSION_SECRET}"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
      JWT_EXPIRES_IN: "${JWT_EXPIRES_IN}"
      DEBUG: "${NODE_DEBUG}"
    depends_on:
      - mongodb
      - redis
